In [1]:
import numpy as np
import pandas as pd

In [16]:
a = [10,20,30,40 , 45.5 , 'aman']

In [17]:
ar = np.array(a)

In [18]:
print(ar)
print(len(ar))
print(type(ar))

['10' '20' '30' '40' '45.5' 'aman']
6
<class 'numpy.ndarray'>


In [19]:
ar.ndim
ar.dtype

dtype('<U32')

In [21]:
b = [[10,20],[30,40],[50,60]]
ar2 = np.array(b)

In [23]:
ar2.ndim
ar2.dtype

dtype('int32')

In [24]:
ar2.shape

(3, 2)

In [25]:
ar2

array([[10, 20],
       [30, 40],
       [50, 60]])

In [27]:
ar3 = np.arange(24)

In [34]:
ar3.reshape(4,6)
ar3.reshape(12,2)
ar3.reshape(6,4)
ar4 = ar3.reshape(2 , 3 ,4 )


In [35]:
ar4.ndim

3

In [ ]:
"""
Pandas:
    Series -> 1d data 
    Dataframe -> 2d data 

"""

In [42]:
s = pd.Series(a , index=["A" , "B" , "C" , "D" , "E" , "F"])

In [39]:
print(type(s))

<class 'pandas.core.series.Series'>


In [43]:
s.index

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

In [46]:
s.values
s.ndim

1

In [47]:
b

[[10, 20], [30, 40], [50, 60]]

In [51]:
df = pd.DataFrame(b , index=["A" , "B" , "C"] , columns=["C1" , "C2"])

In [52]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [56]:
df.index
df.columns
df.values
df.ndim

2

In [57]:
df

C1  C2
A  10  20
B  30  40
C  50  60

In [58]:
s

A      10
B      20
C      30
D      40
E    45.5
F    aman
dtype: object

In [60]:
google = pd.read_csv(r"C:\Users\PC\Desktop\datasets\google_stock_price.csv")

In [62]:
google = google.squeeze()

In [68]:
#python functions on Pandas Series
len(google)
max(google)
min(google)
sum(google)
sorted(google)

[49.95,
 50.07,
 50.12,
 50.7,
 50.74,
 50.95,
 51.1,
 51.1,
 51.13,
 52.38,
 52.61,
 52.95,
 53.02,
 53.7,
 53.9,
 54.1,
 54.65,
 55.69,
 55.94,
 56.93,
 58.69,
 58.86,
 59.07,
 59.13,
 59.62,
 59.86,
 60.35,
 63.37,
 64.74,
 65.47,
 66.22,
 67.46,
 67.56,
 68.47,
 68.63,
 68.8,
 69.12,
 69.36,
 70.17,
 70.38,
 70.93,
 71.98,
 73.9,
 74.51,
 74.62,
 82.47,
 83.68,
 83.69,
 83.85,
 84.27,
 84.59,
 84.62,
 84.91,
 85.14,
 85.63,
 85.74,
 86.13,
 86.16,
 86.19,
 86.19,
 86.63,
 87.29,
 87.41,
 87.71,
 88.06,
 88.15,
 88.47,
 88.81,
 89.21,
 89.22,
 89.26,
 89.4,
 89.54,
 89.56,
 89.61,
 89.61,
 89.7,
 89.8,
 89.89,
 89.9,
 89.93,
 89.93,
 89.95,
 90.11,
 90.13,
 90.16,
 90.27,
 90.35,
 90.43,
 90.58,
 90.62,
 90.81,
 90.9,
 90.91,
 91.42,
 91.78,
 92.26,
 92.34,
 92.41,
 92.42,
 92.5,
 92.51,
 92.55,
 92.84,
 92.86,
 92.89,
 92.94,
 93.06,
 93.39,
 93.41,
 93.61,
 93.61,
 93.86,
 93.9,
 93.9,
 93.95,
 94.05,
 94.18,
 94.19,
 94.31,
 94.35,
 94.52,
 94.53,
 95.07,
 95.22,
 95.59,
 95.6,
 

In [74]:
#series attributes 
google.ndim
google.shape
google.size
google.dtype
google.index
google.values

array([ 50.12,  54.1 ,  54.65, ..., 773.18, 771.61, 782.22])

In [90]:
#some of Pandas Series Methods
google.head()
google.head(3)
google.tail()
google.tail(3)
google.max()
google.min()
google.sum()
google.count()
google.mean()
google.sum()/google.count()
google.median()
google.mode()
google.std()
google.describe()

count    3012.000000
mean      334.310093
std       173.187205
min        49.950000
25%       218.045000
50%       283.315000
75%       443.000000
max       782.220000
Name: Stock Price, dtype: float64

In [94]:
google.is_unique
google.nunique()
google.unique()

array([ 50.12,  54.1 ,  54.65, ..., 773.18, 771.61, 782.22])

In [97]:
google.sort_values(ascending=False)

3011    782.22
2859    776.60
3009    773.18
3007    772.88
3010    771.61
         ...  
12       50.74
10       50.70
0        50.12
9        50.07
11       49.95
Name: Stock Price, Length: 3012, dtype: float64

In [102]:
google[0]
google[[145,561,2956]]
google[584:590]

584    240.65
585    239.26
586    240.82
587    239.91
588    231.17
589    234.08
Name: Stock Price, dtype: float64

In [106]:
pokemon = pd.read_csv(r"C:\Users\PC\Desktop\datasets\pokemon.csv" , usecols = ["Pokemon"])
pokemon = pokemon.squeeze()

In [109]:
pokemon.nunique()
pokemon.is_unique

True

In [111]:
"Bulbasaur" in pokemon

False

In [112]:
pokemon

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...    
716       Yveltal
717       Zygarde
718       Diancie
719         Hoopa
720     Volcanion
Name: Pokemon, Length: 721, dtype: object

In [115]:
pokemon = pd.read_csv(r"C:\Users\PC\Desktop\datasets\pokemon.csv" , index_col="Pokemon" )
pokemon = pokemon.squeeze()

In [116]:
pokemon

Pokemon
Bulbasaur       Grass
Ivysaur         Grass
Venusaur        Grass
Charmander       Fire
Charmeleon       Fire
               ...   
Yveltal          Dark
Zygarde        Dragon
Diancie          Rock
Hoopa         Psychic
Volcanion        Fire
Name: Type, Length: 721, dtype: object

In [119]:
pokemon["Bulbasaur"]
pokemon[["Bulbasaur" , "Charmeleon"]]
pokemon["Bulbasaur" : "Charmeleon"]

Pokemon
Bulbasaur     Grass
Ivysaur       Grass
Venusaur      Grass
Charmander     Fire
Charmeleon     Fire
Name: Type, dtype: object

In [121]:
pokemon["aman"]

KeyError: 'aman'

In [125]:
pokemon.get("Bulbasaur")
pokemon.get("aman" , default="Not a valid Pokemon")

'Not a valid Pokemon'